version: "3.0"

services:

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@emaill.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 15432:80
    networks:
      - postgres_network

  postgres:
    image: postgres
    networks:
      - postgres_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

networks:
  postgres_network:
    driver: bridge